theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"
popup-border = "all"
color-modes = true
soft-wrap.enable = true
completion-trigger-len = 1
completion-replace = true
completion-timeout = 100
end-of-line-diagnostics = "hint"
auto-format = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.lsp]
display-messages = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
"S-tab" = ":buffer-previous"

[keys.normal.space]
i = ":toggle-option lsp.display-inlay-hints"
v = ":sh alacritty"
