# NIX

[[language]]
name = "nix"
auto-format = true
formatter.command = "nixfmt"

# RUST

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
provideFormatter = true
cargo.features = "all"

[language-server.rust-analyzer.config.inlayHints]
bindingModeHints.enable = false 
closingBraceHints.minLines = 10
closureReturnTypeHints.enable = "with_block"
discriminantHints.enable = "fieldless"
lifetimeElisionHints.enable = "skip_trivial"
typeHints.hideClosureInitialization = false

# HASKELL

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "hs|haskell"
file-types = ["hs", "hs-boot", "hsc"]
roots = ["Setup.hs", "stack.yaml", "cabal.project"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
language-servers = [ "haskell-language-server" ]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language-server.haskell-language-server.config]
haskell.formattingProvider = "stylish-haskell"
haskell.plugin.rename.config.crossModule = true

# PYTHON

[[language]]
name = "python"
language-servers = ["ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]
