format = """
[░▒▓](black)\
$username\
[](bg:blue fg:black)\
$directory\
[](fg:blue bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#2b3248)\
$rust\
$haskell\
$python\
$c\
[](fg:#2b3248 bg:#1d2230)\
$nix_shell\
[](fg:#1d2230)\
\n$character"""

# add_newline = false

[username]
disabled = false
show_always = true
style_user = "bg:black fg:bright-white"
format = '[ $user ]($style)'

[directory]
style = "bold fg:black bg:blue"
format = "[ $path ]($style)"
# truncate_to_repo = false
# truncation_length = 50
# truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:bright-cyan bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_status]
deleted = "x"
style = "fg:cyan bg:#394260"
format = '[$all_status$ahead_behind ]($style)'

[python]
symbol = "󰌠"
style = "fg:bright-blue bg:#2b3248"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:bright-blue bg:#2b3248"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "fg:bright-blue bg:#2b3248"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = ""
style = "fg:bright-blue bg:#2b3248"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
disabled = false
impure_msg = "[ ](fg:purple bg:#1d2230)"
pure_msg = "[ ](fg:green bg:#1d2230)"
unknown_msg = "[ ](fg:blue bg:#1d2230)"
format = '[ $state ($name) ](fg:blue bg:#1d2230)'
