[theme]
theme = "native"

[theme.overrides]

good_fg = "#7DCFFF"
info_fg = "#7AA2F7"
warning_fg = "#E0AF68"
critical_fg = "#F7768E"

good_bg = "#7DCFFF33"
info_bg = "#7AA2F733"
warning_bg = "#E0AF6833"
critical_bg = "#F7768E33"

# separator = "•"

icons_format = "{icon}"
[icons.overrides]
backlight = "BRI"

[[block]]
block = "cpu"
info_cpu = 20
interval = 1
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "custom"
interval = 1
command = '''
#!/usr/bin/env bash

gpu_util=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)

if [ "$gpu_util" -ge 0 ] && [ "$gpu_util" -le 25 ]; then
    state="idle"
elif [ "$gpu_util" -ge 25 ] && [ "$gpu_util" -le 50 ]; then
    state="info"
elif [ "$gpu_util" -gt 50 ] && [ "$gpu_util" -le 75 ]; then
    state="warning"
else
    state="critical"
fi

gpu_text=$(printf "%2d" "$gpu_util")

echo "{\"state\": \"$state\", \"text\": \"GPU ${gpu_text}%\"}"
'''
json = true
shell = "bash"
format = " $text.pango-str() "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
interval = 20
warning = 200.0
alert = 250.0
format = " $icon $percentage.eng(w:2) "

[[block]]
block = "net"
format = " $icon $speed_down.eng(prefix:K) $speed_up.eng(prefix:K) "
inactive_format = "<span foreground='#F7767E' background='#F7768E33'> DISCONNECTED </span>"

[[block]]
block = "backlight"

[[block]]
block = "bluetooth"
mac = "60:AB:D2:90:01:3E"
disconnected_format = ""
format = " $name{ $percentage|} "

[[block]]
block = "bluetooth"
mac = "F4:B6:2D:47:B1:32"
disconnected_format = ""
format = " $name{ $percentage|} "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
if_command = "cat /sys/class/power_supply/BAT0/capacity"
full_format = " $icon $percentage "
good = 95
info = 40
warning = 35
critical = 15

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%R %d/%m/%y') "
